library(tidyverse)

start_time <- Sys.time()


average_range <- function(values) {
    values <- str_replace_all(values, "<=", "0-")
    c <- length(values)+1
    for (i in 1:c) {
        if (!is.na(values[i]) & str_detect(values[i] , '[0-9]-[0-9]')) {
            s <- as.numeric(unlist(str_split(values[i], '-')))
            values[i] <- mean(s)
        }
    }

    return(unlist(values))
}





#cols <- "iccccccfcciiiiiiiiiiinniiiiiiiiiiiiinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnniniiiinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnninnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnniiiiiiiiiiiiiininnnniiiiiinniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnninnnnnnnnniinnnnnnnnnnninnnnniiiiiiiiiiiiiiiiinniiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnninnniinniiinnnninnnnnnnnnnnnnnnnnnnnnncnncnnnnninninniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiicifcnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnininnnnininnnnininnnnininnnniiiinnnnnnnnnnnnnnnnnnnniiifffffffccccciiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnniiiinniiiiiiiiiiiininiininiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddniddninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnnidididciiiiiiddiinnnnnnininnninnnnnnnnnnnnnnnnnnnninnnninnnninnnninnnniiiinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnniiinniiiiiiiniiiiiiiiiiiiiiniiiiiiinnnnnnnnnnnniiiiiiinnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnninnnnnnnncnnnnnnnnnnnnniiic"

#insts <- read_csv("data/Most-Recent-Cohorts-Institution.csv", col_type=cols, na=c("NULL", "PrivacySuppressed"))
insts <- read_csv("data/Most-Recent-Cohorts-Institution.csv", na=c("NULL", "PrivacySuppressed"))

insts <- data.frame(sapply(insts, average_range))

write_csv(insts, "insts.csv")

end_time <- Sys.time()

print(end_time - start_time)
